[package]
name = "osu-api"
version = "0.1.0"
authors = ["TicClick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.0.0"
reqwest = "0.11"
